services:
  talent-hub_pgdatabase:
    container_name: talent-hub_pgdatabase
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend

  talent-hub_bucket:
    container_name: talent-hub_bucket
    image: minio/minio
    ports:
      - "${BUCKET_PORT}:9000"
      - "${BUCKET_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${BUCKET_USER}
      MINIO_ROOT_PASSWORD: ${BUCKET_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - backend

  talent-hub_cache:
    container_name: talent-hub_cache
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_cache:/data/redis
    networks:
      - backend

volumes:
  redis_cache:
  postgres_data:
  minio-data:

networks:
  backend:
    driver: bridge
