version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: talent-hub_pgdatabase
    environment:
      POSTGRES_USER: talent-hub_admin
      POSTGRES_PASSWORD: talent-hub_admin_11231233
      POSTGRES_DB: talent-hub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: talent-hub_admin
      MINIO_ROOT_PASSWORD: talent-hub_admin_11231233
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"  
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - minio_network

volumes:
  minio-data:
    driver: local
  postgres_data:
    driver: local

networks:
  minio_network:
    driver: bridge