version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: talent-hub_pgdatabase
    environment:
      POSTGRES_USER: talent-hub_admin
      POSTGRES_PASSWORD: talent-hub_admin_11231233
      POSTGRES_DB: talent-hub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data: