services:
  talent-hub_pgdatabase:
    container_name: talent-hub_pgdatabase
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend

  talent-hub_bucket:
    container_name: talent-hub_bucket
    image: minio/minio
    ports:
      - "${BUCKET_PORT}:${BUCKET_PORT}"
      - "${BUCKET_CONSOLE_PORT}:${BUCKET_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${BUCKET_USER}
      MINIO_ROOT_PASSWORD: ${BUCKET_PASSWORD}
    command: server /data --console-address ":${BUCKET_CONSOLE_PORT}"
    volumes:
      - minio-data:/data
    networks:
      - backend

  talent-hub_cache:
    container_name: talent-hub_cache
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./.redis:/usr/local/etc/redis
      - redis_cache:/data/redis
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - backend

volumes:
  redis_cache:
  postgres_data:
  minio-data:

networks:
  backend:
    driver: bridge
