@base_url = https://localhost:7014/api

# Candidates

### Get Candidate By Id
@id=""
GET {{base_url}}/candidates/{{id}}
Accept: application/json
###

### Get All Candidates
@limit=10
@offset=0
@get_candidate_sort_by=Id
@get_candidate_sort_ascending=true
GET {{base_url}}/candidates?_limit={{limit}}&_offset={{offset}}&_sort_by={{get_candidate_sort_by}}&_sort_ascending={{get_candidate_sort_ascending}}
###