using Ardalis.SmartEnum;

namespace TalentHub.ApplicationCore.Candidates.Enums;

public class Language(string name, int value) : SmartEnum<Language>(name, value)
{
    public static readonly Language Afrikaans = new("afrikaans", 1);
    public static readonly Language Albanian = new("albanian", 2);
    public static readonly Language Arabic = new("arabic", 3);
    public static readonly Language Armenian = new("armenian", 4);
    public static readonly Language Azerbaijani = new("azerbaijani", 5);
    public static readonly Language Bengali = new("bengali", 6);
    public static readonly Language Bosnian = new("bosnian", 7);
    public static readonly Language Bulgarian = new("bulgarian", 8);
    public static readonly Language Catalan = new("catalan", 9);
    public static readonly Language Chinese = new("chinese", 10);
    public static readonly Language Croatian = new("croatian", 11);
    public static readonly Language Czech = new("czech", 12);
    public static readonly Language Danish = new("danish", 13);
    public static readonly Language Dutch = new("dutch", 14);
    public static readonly Language English = new("english", 15);
    public static readonly Language Estonian = new("estonian", 16);
    public static readonly Language Finnish = new("finnish", 17);
    public static readonly Language French = new("french", 18);
    public static readonly Language Georgian = new("georgian", 19);
    public static readonly Language German = new("german", 20);
    public static readonly Language Greek = new("greek", 21);
    public static readonly Language Gujarati = new("gujarati", 22);
    public static readonly Language Hebrew = new("hebrew", 23);
    public static readonly Language Hindi = new("hindi", 24);
    public static readonly Language Hungarian = new("hungarian", 25);
    public static readonly Language Icelandic = new("icelandic", 26);
    public static readonly Language Indonesian = new("indonesian", 27);
    public static readonly Language Irish = new("irish", 28);
    public static readonly Language Italian = new("italian", 29);
    public static readonly Language Japanese = new("japanese", 30);
    public static readonly Language Kannada = new("kannada", 31);
    public static readonly Language Kazakh = new("kazakh", 32);
    public static readonly Language Korean = new("korean", 33);
    public static readonly Language Latvian = new("latvian", 34);
    public static readonly Language Lithuanian = new("lithuanian", 35);
    public static readonly Language Macedonian = new("macedonian", 36);
    public static readonly Language Malay = new("malay", 37);
    public static readonly Language Malayalam = new("malayalam", 38);
    public static readonly Language Maltese = new("maltese", 39);
    public static readonly Language Marathi = new("marathi", 40);
    public static readonly Language Mongolian = new("mongolian", 41);
    public static readonly Language Nepali = new("nepali", 42);
    public static readonly Language Norwegian = new("norwegian", 43);
    public static readonly Language Persian = new("persian", 44);
    public static readonly Language Polish = new("polish", 45);
    public static readonly Language Portuguese = new("portuguese", 46);
    public static readonly Language Punjabi = new("punjabi", 47);
    public static readonly Language Romanian = new("romanian", 48);
    public static readonly Language Russian = new("russian", 49);
    public static readonly Language Serbian = new("serbian", 50);
    public static readonly Language Slovak = new("slovak", 51);
    public static readonly Language Slovenian = new("slovenian", 52);
    public static readonly Language Spanish = new("spanish", 53);
    public static readonly Language Swahili = new("swahili", 54);
    public static readonly Language Swedish = new("swedish", 55);
    public static readonly Language Tamil = new("tamil", 56);
    public static readonly Language Telugu = new("telugu", 57);
    public static readonly Language Thai = new("thai", 58);
    public static readonly Language Turkish = new("turkish", 59);
    public static readonly Language Ukrainian = new("ukrainian", 60);
    public static readonly Language Urdu = new("urdu", 61);
    public static readonly Language Uzbek = new("uzbek", 62);
    public static readonly Language Vietnamese = new("vietnamese", 63);
    public static readonly Language Welsh = new("welsh", 64);
    public static readonly Language Xhosa = new("xhosa", 65);
    public static readonly Language Zulu = new("zulu", 66);
}
